#!/bin/bash

source calc
source search
source reverse
source strlen
source _exit


case  "$1" in
 "calc")
calc "$2" "$3" "$4";;
"search")
search "$2" "$3";;
"reverse")
reverse "$2" "$3";;
"strlen")
strlen "$2";;
"exit")
_exit "$2";;
esac
