#!/bin/bash
for pid in $(ps -Ao pid | tail -n +2); do
	f='/proc/'$pid
	ppid=$(grep -Ehsi "ppid" $f"/status" | grep -o "[0-9]\+")
	rtime=$(grep -Ehsi "se\.sum_exec_runtime" $f"/sched" | awk '{print $3}')
	swtc=$(grep -Ehsi "nr_switches" $f"/sched" | awk '{print $3}')
	if [ -z $ppid ]; then ppid=0 ;fi
	if [ -z $rtime ] || [ -z $swtc ]; then ART=0; else
		ART=$(printf "$rtime $swtc" | awk '{printf("%f",$1/$2)}')
	fi
	echo "$pid $ppid $ART"
done | sort -nk2 | awk '{print "ProcessID="$1" : Parent_ProcessID="$2" : Average_Running_Time="$3}' > res.forth.txt
